version: "3"

services:
  aria2-pro:
    container_name: aria2
    image: 38f9f84eca44
    environment:
      PUID: 65534
      PGID: 65534
      RPC_SECRET: secret
      RPC_PORT: 46800
      LISTEN_PORT: 46234
      UPDATE_TRACKERS: 'true'
      TZ: Asia/Shanghai
      SPECIAL_MODE: rclone
      CUSTOM_TRACKER_URL: 'https://cdn.jsdelivr.net/gh/Apocalypsor/Aria2-ProMax@tracker/all.list'
    volumes:
      - ./test/config:/config
    ports:
      - 46800:46800
      - 46234:46234
      - 46234:46234/udp
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
