name: Update Trackers

on:
  workflow_dispatch:
  
  push:
    branches:
      - master
    paths:
      - .github/workflows/Tracker.yaml
  
  schedule:
    - cron: 23 8 * * *

jobs:
  Update-Tacker:
    runs-on: ubuntu-latest
    name: Update Tracker
    steps:
    - uses: actions/checkout@v2
      with:
        ref: tracker
        token: ${{ secrets.REPO_TOKEN }}
    - name: Smartdns GFWList
      run: |
        echo > /tmp/blank

        curl -sSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt > /tmp/all
        curl -sSL https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt > /tmp/AT_all
        cat /tmp/all /tmp/blank /tmp/AT_all | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | tr -d "\n" > all.list
        cat /tmp/all /tmp/blank /tmp/AT_all | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | sed -e "s/,/\n/g" > all_raw.list

        curl -sSL https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/best.txt > /tmp/best
        curl -sSL https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_best.txt > /tmp/AT_best
        cat /tmp/best /tmp/blank /tmp/AT_best | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | tr -d "\n" > best.list
        cat /tmp/best /tmp/blank /tmp/AT_best | uniq | sed ":a;N;s/\n/,/g;ta" | sed -e "s/,,/,/g" -e "s/,$//g" | sed -e "s/,/\n/g" > best_raw.list
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: tracker
        commit_message: Update Trackers
        skip_dirty_check: false
        commit_user_name: Action Bot
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: Action <actions@github.com>
